### ISSUE TITLE
Hey Bro

### ISSUE THREAD

**Issue by VerseChow** [fnivek/fnivek.github.io#1]
Hey man! Hope you are doing well! How are you thesedays? Really miss you. It turns out to be boring without you by my side. And I am looking forward to seeing your website update!

**Comment by fnivek** [comment]
Miss you too Verse. This gives me some incentive to get my website up.

**Comment by VerseChow** [comment]
HHHa! Hope I can be the first one who browse it.

**Comment by fnivek** [comment]
Website is up! Still need to add things to the website but I am happy enough with it to start promoting it.
